version: "3"

services:

    web_ad:
        build: ./web
        restart: always
        environment:
            - APACHE_RUN_USER=#1000
        volumes:
            - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
        ports:
            - 10080:80
        working_dir: ${APP_PATH_CONTAINER}

    db_ad:
        build: ./db
        command: "--innodb_use_native_aio=0 --default-authentication-plugin=mysql_native_password"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ad.api_db
        volumes:
            - ${DB_PATH_HOST}:/var/lib/mysql

    phpmyadmin_ad:
        build: ./phpmyadmin
        links:
            - db_ad
        restart: always
        ports:
            - 10081:80
        environment:
            - PMA_HOST=db_ad
            - PMA_PORT=3306
            - PMA_ARBITRARY=1

    composer_ad:
        image: composer
        volumes:
            - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
        working_dir: ${APP_PATH_CONTAINER}
        command: composer install
